## **one dimentional arrays**

In [32]:
import numpy as np

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [9]:
a[1]

np.int64(2)

In [15]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0,1, 21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

## **multidimentional arrays**

In [18]:
np.zeros((5, 2))


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
p =np.ones((5, 2))
p


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
p[1]

array([1., 1.])

In [24]:
np[1]

array([1., 1.])

In [56]:
np.random.seed(24)
np.random.rand(10, 4)

array([[0.9600173 , 0.69951205, 0.99986729, 0.2200673 ],
       [0.36105635, 0.73984099, 0.99645573, 0.31634698],
       [0.13654458, 0.38398001, 0.32051928, 0.36641475],
       [0.70965156, 0.90014243, 0.53411544, 0.24729376],
       [0.67180656, 0.56172911, 0.54255988, 0.8934476 ],
       [0.84277955, 0.30601259, 0.63116978, 0.68023886],
       [0.97042756, 0.89356715, 0.94242586, 0.64222548],
       [0.61464763, 0.22768325, 0.48603187, 0.8072193 ],
       [0.84422015, 0.53468087, 0.75779805, 0.49967689],
       [0.8503279 , 0.61969678, 0.86161418, 0.2316972 ]])

In [57]:
np.random.randn(10, 4)

array([[ 1.68658289, -1.32596315,  1.4289837 , -2.08935428],
       [-0.12981994,  0.63152295, -0.58653806,  0.29072008],
       [ 1.26410337,  0.29003478, -1.9702885 ,  0.80390589],
       [ 1.03055033,  0.11809794, -0.02185333,  0.04684071],
       [-1.62875286, -0.39236059,  1.70097271,  1.06132976],
       [ 0.69580357, -0.43598857, -0.33294162,  0.60213456],
       [ 0.10878896,  0.03676693, -0.53896341,  0.49917789],
       [-0.71195176, -0.23700097,  0.85711924, -1.8823519 ],
       [ 0.42070509, -1.06917534, -2.5768588 , -1.22492344],
       [-1.15675186,  0.93130427,  0.98425715,  2.22615937]])

In [63]:
np.random.seed(24)
array = np.random.randint(0, 100, (10, 4))
array

array([[34,  3, 64, 87],
       [17, 17,  1, 79],
       [ 4, 99, 82, 11],
       [99, 15, 73, 18],
       [ 7, 25, 35, 95],
       [28,  0, 12, 95],
       [33,  1, 60, 55],
       [70, 97, 81,  6],
       [46, 65, 47, 89],
       [74, 35, 64, 27]], dtype=int32)

In [76]:
array[:,0]

array([34, 17,  4, 99,  7, 28, 33, 70, 46, 74], dtype=int32)

In [84]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b + c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [85]:
b * 4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [86]:
b * c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [88]:
b.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [81]:
array[0, 1]

np.int32(3)

In [82]:
array[0].sum()

np.int64(188)

In [83]:
array[0].max()

np.int32(87)

In [91]:
def matrix_matrix_multiplicatioin(a, b):
    assert a.shape[1] == b.shape[0], "Number of columns in a must be equal to number of rows in b"
    num_rows_a = a.shape[0]
    num_cols_b = b.shape[1]
    results = np.zeros((a.shape[0], b.shape[1]))

    # for i in range(num_rows_a):
    #     for j in range(num_cols_b):
    #         results[i, j] = np.dot(a[i, :], b[:, j])
    for i in range(num_rows_a):
        for j in range(num_cols_b):
            results[i, j] = np.dot(a[i, :], b[:, j])

    return results

In [92]:
matrix_matrix_multiplicatioin(b, c)

array([[ 30.,  36.,  42.],
       [ 66.,  81.,  96.],
       [102., 126., 150.]])

In [97]:
A = [[1, 2, 3],
     [4, 5, 6]]

B = [[7, 8],
     [9, 10],
     [11, 12]]

result = np.zeros((len(A), len(B[0])))


for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]

for row in result:
    print(row)

[58. 64.]
[139. 154.]


In [95]:
len(b[0])

3

In [100]:
np.linalg.inv(b)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])